apiVersion: v1
kind: Pod
metadata: 
  name: label-pod1
  labels:
    creation_method: manual
    env: prod
spec:
  containers:
  - image: ahsankhan0061/com_image1
    name: mynode-cont1
    ports:
    - containerPort: 8080   
