apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2020-01-14T14:29:30Z"
  name: firstpod
  namespace: default
  resourceVersion: "9909"
  selfLink: /api/v1/namespaces/default/pods/firstpod
  uid: 5d00c5ca-e199-436f-bcb8-3e8f2a6b7d6e
spec:
  containers:
  - image: ahsankhan0061/my-first-docker-app
    imagePullPolicy: Always
    name: firstcontainer
    ports:
    - containerPort: 80
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-647ps
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: minikube
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-647ps
    secret:
      defaultMode: 420
      secretName: default-token-647ps
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-01-14T14:29:30Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-01-14T14:34:01Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-01-14T14:34:01Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-01-14T14:29:30Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://73070d7340ee946e22a473fc22021deb53741d9b29982a63522971a56fb76b84
    image: ahsankhan0061/my-first-docker-app:latest
    imageID: docker-pullable://ahsankhan0061/my-first-docker-app@sha256:e3cda04a9f8c76f3ea85d74464925b85b82e7425c5b0fd3494933eac78b3ad60
    lastState: {}
    name: firstcontainer
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2020-01-14T14:34:00Z"
  hostIP: 192.168.99.100
  phase: Running
  podIP: 172.17.0.4
  podIPs:
  - ip: 172.17.0.4
  qosClass: BestEffort
  startTime: "2020-01-14T14:29:30Z"
