kind: ReplicaSet
apiVersion: apps/v1
metadata:
  name: first-replica-set
spec:
  replicas: 3
  selector:
    matchLabels:
      app: replica-app
    matchExpressions:
      - {key: tier, operator: In, values: [frontend]}
  template:
    metadata:
      name: rep-pod
      labels:
        app: replica-app
        tier: frontend
    spec:
      containers:
      - name: mynode-cont1
        image: ahsankhan0061/com_image1
        ports:
        - containerPort: 80
             
