apiVersion: v1
kind: Pod
metadata:
  name: test-edv
spec:
  containers:
  - image: k8s.gcr.io/test-webserver
    name: test-cont
    volumeMounts:
    - name: cache-vol
      mountPath: /cache
  volumes:
  - name: cache-vol
    emptyDir: {} 
